#!/bin/bash
#------------------------------
#  0dev
#  Software development comapny
#  https://odev.co
#------------------------------

# bash-now default alias >>  @code4mk

alias me='whoami'
alias live='live-server'
alias 0='clear'
