#!/bin/bash
#------------------------------
#  0dev
#  Software development comapny
#  https://odev.co
#------------------------------

# LARAVEL alias >>  @code4mk

# read laravel alias lists
alias a.read='cat ~/bash-alias/laravel'
# artisan core
alias a.='php artisan'
alias a.v='php artisan --version'
alias a.ls='php artisan list'
alias a.help='php artisan help'
alias a.s='php artisan serve'
alias a.up='php artisan up'
alias a.down='php artisan down'
alias a.new='laravel new'
# key generate
alias a.key='php artisan key:generate'
# tinker
alias a.tinker='php artisan tinker'
# generating command
alias a.m.command='php artisan make:command'
# make auth
alias a.m.auth='php artisan make:auth'
# make authorization
alias a.m.policy='php artisan make:policy'
# make controller
alias a.m.controller='php artisan make:controller'
# route
alias a.r.ls='php artisan route:list'
alias a.r.cache='php artisan route:cache'
alias a.r.clear='php artisan route:clear'
# middleware
alias a.m.ware='php artisan make:middleware'
# eloquent model
alias a.m.model='php artisan make:model'
alias a.m.observer='php artisan make:observer'
# database
alias a.m.mg='php artisan make:migration'
alias a.m.factory='php artisan make:factory'
alias a.mg='php artisan migrate'
alias a.mg.install='php artisan migrate:install'
alias a.mg.fresh='php artisan migrate:fresh'
alias a.mg.refresh='php artisan migrate:refresh'
alias a.mg.reset='php artisan migrate:reset'
alias a.mg.rollback='php artisan migrate:rollback'
alias a.mg.status='php artisan migrate:status'
# frontend
alias a.preset='php artisan preset'
alias a.view='php artisan view:clear'
# resource
alias a.m.resource='php artisan make:resource'
# file system
alias a.storage='php artisan storage:link'
# event
alias a.event='php artisan event:generate'
# mail
alias a.m.mail='php artisan make:mail'
# make
alias a.m.exception='php artisan make:exception'
alias a.m.job='php artisan make:job'
alias a.m.listener='php artisan make:listener'
alias a.m.provider='php artisan make:provider'
alias a.m.request='php artisan make:request'
alias a.m.rule='php artisan make:rule'
alias a.m.seeder='php artisan make:seeder'
alias a.m.test='php artisan make:test'
# notification
alias a.m.noti='php artisan make:notification'
alias a.noti='php artisan notifications:table'
# cache
alias a.ca.clear='php artisan cache:clear'
alias a.ca.forget='php artisan cache:forget'
alias a.ca.table='php artisan cache:table'
# schedule
alias a.schedule='php artisan schedule:run'
# queue
alias a.q.fail='php artisan queue:failed'
alias a.q.fail.t='php artisan queue:failed-table'
alias a.q.flush='php artisan queue:flush'
alias a.q.forget='php artisan queue:forget'
alias a.q.listen='php artisan queue:listen'
alias a.q.restart='php artisan queue:restart'
alias a.q.retry='php artisan queue:retry'
alias a.q.table='php artisan queue:table'
alias a.q.work='php artisan queue:work'
#session
alias a.ses='php artisan session:table'
# vendor
alias a.vendor='php artisan vendor:publish'
# deployment
alias a.cf.cache='php artisan config:cache'
alias a.cf.clear='php artisan config:cache'

# composer
alias cm.='composer'
alias cm.v='composer --version'
alias cm.help='composer --help'
alias cm.create='composer create-project'
alias cm.in='composer install'
alias cm.remove='composer remove'
alias cm.out='composer outdated'
alias cm.up='composer update'
alias cm.ini='composer init'
alias cm.dump='composer dump-autoload'
alias cm.cache='composer clear-cache'
alias cm.r='composer require'
alias cm.g.r='composer global require'
